apiVersion: apps/v1
kind: Deployment
metadata:
  name: dongnguyen.dev-deployment
  labels:
    app: dongnguyen.dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dongnguyen.dev
  template:
    metadata:
      labels:
        app: dongnguyen.dev
    spec:
      containers:
        - name: dongnguyen.dev
          image: 622511097532.dkr.ecr.ap-southeast-1.amazonaws.com/dongnguyen.dev:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "200m"
              memory: "500Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: dongnguyen.dev
spec:
  type: NodePort
  selector:
    app: dongnguyen.dev
  ports:
    - name: http8000
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30205
