steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "asia.gcr.io/tough-racer-272817/blog:$SHORT_SHA", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia.gcr.io/tough-racer-272817/blog:$SHORT_SHA"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "tag",
        "asia.gcr.io/tough-racer-272817/blog:$SHORT_SHA",
        "asia.gcr.io/tough-racer-272817/blog:latest",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia.gcr.io/tough-racer-272817/blog:latest"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - beta
      - run
      - deploy
      - --region=asia-east1
      - --image=asia.gcr.io/tough-racer-272817/blog:latest
      - --cpu=1
      - --memory=128Mi
      - --max-instances=1
      - --platform=managed
      - --port=3000
      - --concurrency=1000
      - --allow-unauthenticated
      - blog
images:
  - "asia.gcr.io/tough-racer-272817/blog:latest"
